// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6vtiMdF8zW1AfnmL2cAkpZgTT66yX2HE',
    appId: '1:990070719972:web:ec245186a8e2f62ca273f1',
    messagingSenderId: '990070719972',
    projectId: 'findadoc-bb0ce',
    authDomain: 'findadoc-bb0ce.firebaseapp.com',
    storageBucket: 'findadoc-bb0ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb_SrL1bZ3Kid6PDeQVmFwnmpR1KfMGZc',
    appId: '1:990070719972:android:ff710248da19b7d7a273f1',
    messagingSenderId: '990070719972',
    projectId: 'findadoc-bb0ce',
    storageBucket: 'findadoc-bb0ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH3XU8O4inPpiTZ1VI6cIdMq4LQ0uGCnA',
    appId: '1:990070719972:ios:8578a7d9b980c1d0a273f1',
    messagingSenderId: '990070719972',
    projectId: 'findadoc-bb0ce',
    storageBucket: 'findadoc-bb0ce.appspot.com',
    iosClientId: '990070719972-upb86bruspr8veb5ur99v7pvmtkprt31.apps.googleusercontent.com',
    iosBundleId: 'com.example.findadoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH3XU8O4inPpiTZ1VI6cIdMq4LQ0uGCnA',
    appId: '1:990070719972:ios:8578a7d9b980c1d0a273f1',
    messagingSenderId: '990070719972',
    projectId: 'findadoc-bb0ce',
    storageBucket: 'findadoc-bb0ce.appspot.com',
    iosClientId: '990070719972-upb86bruspr8veb5ur99v7pvmtkprt31.apps.googleusercontent.com',
    iosBundleId: 'com.example.findadoc',
  );
}
